# ██╗     ██╗████████╗███████╗██╗    ██╗ █████╗ ██████╗ ███████╗
# ██║     ██║╚══██╔══╝██╔════╝██║    ██║██╔══██╗██╔══██╗██╔════╝
# ██║     ██║   ██║   █████╗  ██║ █╗ ██║███████║██████╔╝███████╗
# ██║     ██║   ██║   ██╔══╝  ██║███╗██║██╔══██║██╔══██╗╚════██║
# ███████╗██║   ██║   ███████╗╚███╔███╔╝██║  ██║██║  ██║███████║
# ╚══════╝╚═╝   ╚═╝   ╚══════╝ ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝
#Litewars by NekoEpisode and CysonHab

# 欢迎来到Litewars配置文件！
# 你可以在这里配置Litewars的各项内容

# 插件使用的语言
language: zh_cn

#数据库设置
#插件使用的数据库类型 (SQLite, MySQL)
database-type: "SQLite" #默认SQLite
#仅当类型设置为MySQL时，以下设置才生效(Litewars为MySQL数据库名称)
database-host: "localhost"
database-port: 3306
database-name: "litewars"
database-user: "litewars"
database-password: "litewars@database1101"



