name: Litewars
version: '${project.version}'
main: xyz.litewars.litewars.Litewars
authors:
  - "NekoEpisode"
  - "CYsonHab"

commands:
  version-control:
    description: ""
    permission: Litewars.admin
    aliases: [ "vc" ]

permissions:
  Litewars.admin:
    description: ""
    default: op
  Litewars.tp:
    description: ""
    default: op
