# ██╗     ██╗████████╗███████╗██╗    ██╗ █████╗ ██████╗ ███████╗
# ██║     ██║╚══██╔══╝██╔════╝██║    ██║██╔══██╗██╔══██╗██╔════╝
# ██║     ██║   ██║   █████╗  ██║ █╗ ██║███████║██████╔╝███████╗
# ██║     ██║   ██║   ██╔══╝  ██║███╗██║██╔══██║██╔══██╗╚════██║
# ███████╗██║   ██║   ███████╗╚███╔███╔╝██║  ██║██║  ██║███████║
# ╚══════╝╚═╝   ╚═╝   ╚══════╝ ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝
#Litewars by NekoEpisode and CysonHab

# 欢迎来到Litewars配置文件！
# 你可以在这里配置Litewars的各项内容

# 插件使用的语言
language: zh_cn






