#     __    _ __
#    / /   (_) /____ _      ______ ___________
#   / /   / / __/ _ \ | /| / / __ `/ ___/ ___/
#  / /___/ / /_/  __/ |/ |/ / /_/ / /  (__  )
# /_____/_/\__/\___/|__/|__/\__,_/_/  /____/

#Litewars by NekoEpisode and CYsonHab

# 欢迎来到Litewars配置文件！
# 你可以在这里配置Litewars的各项内容

# 插件使用的语言
language: zh_cn

#数据库设置
#插件使用的数据库类型 (SQLite, MySQL)
database-type: "SQLite" #默认SQLite
#仅当类型设置为MySQL时，以下设置才生效
database-host: "localhost"
database-port: 3306
database-name: "litewars"
database-user: "litewars"
database-password: "litewars@database1101"

#控制台相关设置
#是否在控制台展示颜色(仅命令系统)，如果设置为false则命令系统不会显示任何颜色代码，防止无法解析而导致不可读问题
ConsoleColor: true

#Tip系统设置
#是否在玩家在大厅时为他们显示提示信息? (提示信息与切换速度可在Tips.yml自定义)
Tips: true

#主大厅设置
#主大厅聊天格式
LobbyMessageType: "&7[%litewars-lobby_level%] %litewars-lobby_player-name% > {message}"

#杂项
#是否修改加入游戏提示?
EditJoinMessage: true
#如果修改，要修改为什么? (关闭加入提示设置为"") (支持PlaceholderAPI)
#如果您没有安装PlaceholderAPI，我们有几个默认占位符供您使用
# {player} : 将替换为加入的玩家的名称
JoinMessage: "&7{player} >> 加入了游戏"
